name: Deploy Backend Imperio Global

on:
  push:
    branches: [ "main" ] # Se ejecuta automáticamente cuando confirmas cambios en main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Código del Repositorio
      uses: actions/checkout@v4

    - name: Despliegue Remoto por SSH en Contabo
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: '144.126.156.149'
        username: 'root'
        password: ${{ secrets.SSH_PASSWORD }} # Consume el secreto 'Imperioglobal26' de tu captura
        port: 22
        key_checking: false # Evita que GitHub rechace la conexión por firmas de host desconocidas
        script: |
          # 1. Moverse al directorio web contenedor
          cd /var/www
          
          # 2. Si la carpeta fue borrada previamente, clonar el repositorio limpio de GitHub
          if [ ! -d "imperioglobal" ]; then
            git clone https://github.com/yomerysidro/imperio-global-back.git imperioglobal
          fi
          
          # 3. Entrar a la carpeta y desmarcar la advertencia de directorio dudoso de Git
          cd /var/www/imperioglobal
          git config --global --add safe.directory /var/www/imperioglobal
          
          # 4. Forzar la actualización del código al último commit de la rama main
          git fetch --all
          git reset --hard origin/main
          
          # 5. Mover el archivo .env de producción que respaldamos en la raíz
          if [ -f "/root/back_env_backup" ]; then
            cp /root/back_env_backup /var/www/imperioglobal/.env
          fi
          
          # 6. Instalar dependencias de Laravel sin librerías de desarrollo
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # 7. Sincronizar de forma estricta los permisos de propiedad para Nginx
          sudo chown -R www-data:www-data /var/www/imperioglobal
          sudo chmod -R 775 /var/www/imperioglobal/storage /var/www/imperioglobal/bootstrap/cache
          
          # 8. Purgar la caché interna de Laravel y reiniciar el demonio del servidor web
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          sudo systemctl restart nginx