name: Deploy Backend Imperio Global

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Código del Repositorio
      uses: actions/checkout@v4

    - name: Despliegue Remoto por SSH en Contabo
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: '144.126.156.149'
        username: 'root'
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        key_checking: false
        script: |
          # 1. Moverse al directorio web contenedor
          cd /var/www
          
          # 2. Clonar usando el nombre exacto del repositorio si la carpeta no existe
          if [ ! -d "imperio-global-back" ]; then
            git clone https://github.com/yomerysidro/imperio-global-back.git imperio-global-back
          fi
          
          # 3. Entrar a la carpeta correcta y aplicar la excepción de Git
          cd /var/www/imperio-global-back
          git config --global --add safe.directory /var/www/imperio-global-back
          
          # 4. Forzar la actualización del código al último commit de main
          git fetch --all
          git reset --hard origin/main
          
          # 5. Mover el archivo .env de producción que respaldamos en la raíz
          if [ -f "/root/back_env_backup" ]; then
            cp /root/back_env_backup /var/www/imperio-global-back/.env
          fi
          
          # 6. Instalar dependencias de Laravel sin librerías de desarrollo
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # 7. Sincronizar permisos de propiedad para Nginx sobre la nueva ruta
          sudo chown -R www-data:www-data /var/www/imperio-global-back
          sudo chmod -R 775 /var/www/imperio-global-back/storage /var/www/imperio-global-back/bootstrap/cache
          
          # 8. Purgar la caché interna de Laravel y reiniciar el servidor web
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          sudo systemctl restart nginx